version: '3.1'

services:

  app:
    build: ./
    restart: always
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: always
